void* M_deregisterTMCloneTable () { return 0; }
void* M_registerTMCloneTable () { return 0; }
void* polkit_action_description_get_action_id () { return 0; }
void* polkit_action_description_get_annotation () { return 0; }
void* polkit_action_description_get_annotation_keys () { return 0; }
void* polkit_action_description_get_description () { return 0; }
void* polkit_action_description_get_icon_name () { return 0; }
void* polkit_action_description_get_implicit_active () { return 0; }
void* polkit_action_description_get_implicit_any () { return 0; }
void* polkit_action_description_get_implicit_inactive () { return 0; }
void* polkit_action_description_get_message () { return 0; }
void* polkit_action_description_get_type () { return 0; }
void* polkit_action_description_get_vendor_name () { return 0; }
void* polkit_action_description_get_vendor_url () { return 0; }
void* polkit_action_description_new () { return 0; }
void* polkit_action_description_new_for_gvariant () { return 0; }
void* polkit_action_description_to_gvariant () { return 0; }
void* polkit_authority_authentication_agent_response () { return 0; }
void* polkit_authority_authentication_agent_response_finish () { return 0; }
void* polkit_authority_authentication_agent_response_sync () { return 0; }
void* polkit_authority_check_authorization () { return 0; }
void* polkit_authority_check_authorization_finish () { return 0; }
void* polkit_authority_check_authorization_sync () { return 0; }
void* polkit_authority_enumerate_actions () { return 0; }
void* polkit_authority_enumerate_actions_finish () { return 0; }
void* polkit_authority_enumerate_actions_sync () { return 0; }
void* polkit_authority_enumerate_temporary_authorizations () { return 0; }
void* polkit_authority_enumerate_temporary_authorizations_finish () { return 0; }
void* polkit_authority_enumerate_temporary_authorizations_sync () { return 0; }
void* polkit_authority_features_get_type () { return 0; }
void* polkit_authority_get () { return 0; }
void* polkit_authority_get_async () { return 0; }
void* polkit_authority_get_backend_features () { return 0; }
void* polkit_authority_get_backend_name () { return 0; }
void* polkit_authority_get_backend_version () { return 0; }
void* polkit_authority_get_finish () { return 0; }
void* polkit_authority_get_owner () { return 0; }
void* polkit_authority_get_sync () { return 0; }
void* polkit_authority_get_type () { return 0; }
void* polkit_authority_register_authentication_agent () { return 0; }
void* polkit_authority_register_authentication_agent_finish () { return 0; }
void* polkit_authority_register_authentication_agent_sync () { return 0; }
void* polkit_authority_register_authentication_agent_with_options () { return 0; }
void* polkit_authority_register_authentication_agent_with_options_finish () { return 0; }
void* polkit_authority_register_authentication_agent_with_options_sync () { return 0; }
void* polkit_authority_revoke_temporary_authorization_by_id () { return 0; }
void* polkit_authority_revoke_temporary_authorization_by_id_finish () { return 0; }
void* polkit_authority_revoke_temporary_authorization_by_id_sync () { return 0; }
void* polkit_authority_revoke_temporary_authorizations () { return 0; }
void* polkit_authority_revoke_temporary_authorizations_finish () { return 0; }
void* polkit_authority_revoke_temporary_authorizations_sync () { return 0; }
void* polkit_authority_unregister_authentication_agent () { return 0; }
void* polkit_authority_unregister_authentication_agent_finish () { return 0; }
void* polkit_authority_unregister_authentication_agent_sync () { return 0; }
void* polkit_authorization_result_get_details () { return 0; }
void* polkit_authorization_result_get_dismissed () { return 0; }
void* polkit_authorization_result_get_is_authorized () { return 0; }
void* polkit_authorization_result_get_is_challenge () { return 0; }
void* polkit_authorization_result_get_retains_authorization () { return 0; }
void* polkit_authorization_result_get_temporary_authorization_id () { return 0; }
void* polkit_authorization_result_get_type () { return 0; }
void* polkit_authorization_result_new () { return 0; }
void* polkit_authorization_result_new_for_gvariant () { return 0; }
void* polkit_authorization_result_to_gvariant () { return 0; }
void* polkit_check_authorization_flags_get_type () { return 0; }
void* polkit_details_get_keys () { return 0; }
void* polkit_details_get_type () { return 0; }
void* polkit_details_insert () { return 0; }
void* polkit_details_lookup () { return 0; }
void* polkit_details_new () { return 0; }
void* polkit_details_new_for_gvariant () { return 0; }
void* polkit_details_to_gvariant () { return 0; }
void* polkit_error_get_type () { return 0; }
void* polkit_error_quark () { return 0; }
void* polkit_identity_equal () { return 0; }
void* polkit_identity_from_string () { return 0; }
void* polkit_identity_get_type () { return 0; }
void* polkit_identity_hash () { return 0; }
void* polkit_identity_new_for_gvariant () { return 0; }
void* polkit_identity_to_gvariant () { return 0; }
void* polkit_identity_to_string () { return 0; }
void* polkit_implicit_authorization_from_string () { return 0; }
void* polkit_implicit_authorization_get_type () { return 0; }
void* polkit_implicit_authorization_to_string () { return 0; }
void* polkit_permission_get_action_id () { return 0; }
void* polkit_permission_get_subject () { return 0; }
void* polkit_permission_get_type () { return 0; }
void* polkit_permission_new () { return 0; }
void* polkit_permission_new_finish () { return 0; }
void* polkit_permission_new_sync () { return 0; }
void* polkit_subject_equal () { return 0; }
void* polkit_subject_exists () { return 0; }
void* polkit_subject_exists_finish () { return 0; }
void* polkit_subject_exists_sync () { return 0; }
void* polkit_subject_from_string () { return 0; }
void* polkit_subject_get_type () { return 0; }
void* polkit_subject_hash () { return 0; }
void* polkit_subject_new_for_gvariant () { return 0; }
void* polkit_subject_new_for_gvariant_invocation () { return 0; }
void* polkit_subject_to_gvariant () { return 0; }
void* polkit_subject_to_string () { return 0; }
void* polkit_system_bus_name_get_name () { return 0; }
void* polkit_system_bus_name_get_process_sync () { return 0; }
void* polkit_system_bus_name_get_type () { return 0; }
void* polkit_system_bus_name_get_user_sync () { return 0; }
void* polkit_system_bus_name_new () { return 0; }
void* polkit_system_bus_name_set_name () { return 0; }
void* polkit_temporary_authorization_get_action_id () { return 0; }
void* polkit_temporary_authorization_get_id () { return 0; }
void* polkit_temporary_authorization_get_subject () { return 0; }
void* polkit_temporary_authorization_get_time_expires () { return 0; }
void* polkit_temporary_authorization_get_time_obtained () { return 0; }
void* polkit_temporary_authorization_get_type () { return 0; }
void* polkit_temporary_authorization_new () { return 0; }
void* polkit_temporary_authorization_new_for_gvariant () { return 0; }
void* polkit_temporary_authorization_to_gvariant () { return 0; }
void* polkit_unix_group_get_gid () { return 0; }
void* polkit_unix_group_get_type () { return 0; }
void* polkit_unix_group_new () { return 0; }
void* polkit_unix_group_new_for_name () { return 0; }
void* polkit_unix_group_set_gid () { return 0; }
void* polkit_unix_netgroup_get_name () { return 0; }
void* polkit_unix_netgroup_get_type () { return 0; }
void* polkit_unix_netgroup_new () { return 0; }
void* polkit_unix_netgroup_set_name () { return 0; }
void* polkit_unix_process_get_gids () { return 0; }
void* polkit_unix_process_get_owner () { return 0; }
void* polkit_unix_process_get_pid () { return 0; }
void* polkit_unix_process_get_pidfd () { return 0; }
void* polkit_unix_process_get_pidfd_is_safe () { return 0; }
void* polkit_unix_process_get_racy_uid__ () { return 0; }
void* polkit_unix_process_get_start_time () { return 0; }
void* polkit_unix_process_get_type () { return 0; }
void* polkit_unix_process_get_uid () { return 0; }
void* polkit_unix_process_new () { return 0; }
void* polkit_unix_process_new_for_owner () { return 0; }
void* polkit_unix_process_new_full () { return 0; }
void* polkit_unix_process_new_pidfd () { return 0; }
void* polkit_unix_process_set_gids () { return 0; }
void* polkit_unix_process_set_pid () { return 0; }
void* polkit_unix_process_set_pidfd () { return 0; }
void* polkit_unix_process_set_start_time () { return 0; }
void* polkit_unix_process_set_uid () { return 0; }
void* polkit_unix_session_get_session_id () { return 0; }
void* polkit_unix_session_get_type () { return 0; }
void* polkit_unix_session_new () { return 0; }
void* polkit_unix_session_new_for_process () { return 0; }
void* polkit_unix_session_new_for_process_finish () { return 0; }
void* polkit_unix_session_new_for_process_sync () { return 0; }
void* polkit_unix_session_set_session_id () { return 0; }
void* polkit_unix_user_get_name () { return 0; }
void* polkit_unix_user_get_type () { return 0; }
void* polkit_unix_user_get_uid () { return 0; }
void* polkit_unix_user_new () { return 0; }
void* polkit_unix_user_new_for_name () { return 0; }
void* polkit_unix_user_set_uid () { return 0; }
