void* po_file_check_all () { return 0; }
void* po_file_create () { return 0; }
void* po_file_domain_header () { return 0; }
void* po_file_domains () { return 0; }
void* po_file_free () { return 0; }
void* po_filepos_file () { return 0; }
void* po_filepos_start_line () { return 0; }
void* po_file_read () { return 0; }
void* po_file_read_v2 () { return 0; }
void* po_file_read_v3 () { return 0; }
void* po_file_write () { return 0; }
void* po_file_write_v2 () { return 0; }
void* po_format_list () { return 0; }
void* po_format_pretty_name () { return 0; }
void* po_header_field () { return 0; }
void* po_header_set_field () { return 0; }
void* po_message_add_filepos () { return 0; }
void* po_message_check_all () { return 0; }
void* po_message_check_format () { return 0; }
void* po_message_check_format_v2 () { return 0; }
void* po_message_comments () { return 0; }
void* po_message_create () { return 0; }
void* po_message_extracted_comments () { return 0; }
void* po_message_filepos () { return 0; }
void* po_message_insert () { return 0; }
void* po_message_is_format () { return 0; }
void* po_message_is_fuzzy () { return 0; }
void* po_message_is_obsolete () { return 0; }
void* po_message_is_range () { return 0; }
void* po_message_iterator () { return 0; }
void* po_message_iterator_free () { return 0; }
void* po_message_msgctxt () { return 0; }
void* po_message_msgid () { return 0; }
void* po_message_msgid_plural () { return 0; }
void* po_message_msgstr () { return 0; }
void* po_message_msgstr_plural () { return 0; }
void* po_message_prev_msgctxt () { return 0; }
void* po_message_prev_msgid () { return 0; }
void* po_message_prev_msgid_plural () { return 0; }
void* po_message_remove_filepos () { return 0; }
void* po_message_set_comments () { return 0; }
void* po_message_set_extracted_comments () { return 0; }
void* po_message_set_format () { return 0; }
void* po_message_set_fuzzy () { return 0; }
void* po_message_set_msgctxt () { return 0; }
void* po_message_set_msgid () { return 0; }
void* po_message_set_msgid_plural () { return 0; }
void* po_message_set_msgstr () { return 0; }
void* po_message_set_msgstr_plural () { return 0; }
void* po_message_set_obsolete () { return 0; }
void* po_message_set_prev_msgctxt () { return 0; }
void* po_message_set_prev_msgid () { return 0; }
void* po_message_set_prev_msgid_plural () { return 0; }
void* po_message_set_range () { return 0; }
void* po_next_message () { return 0; }
